### ISSUE TITLE
Cannot build the image

### ISSUE THREAD

**Issue by sylvainmetayer** [davescripts/docker-centos-7-apache-php-72#1]
When building the image, I'm having the following error with an exit code (1) : 

```
warning: /var/cache/yum/x86_64/7/base/packages/bind-license-9.11.4-9.P2.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for bind-license-9.11.4-9.P2.el7.noarch.rpm is not installed
Public key for krb5-libs-1.15.1-37.el7_7.2.x86_64.rpm is not installed

Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-6.1810.2.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
error: unpacking of archive failed on file /usr/bin/newgidmap;5d92071d: cpio: cap_set_file
error: shadow-utils-2:4.6-5.el7.x86_64: install failed
```

The error occurs on the first step, `yum update -y`

Is their something specific to do to build the image ?

**Comment by davescripts** [comment]
I haven't had errors when building the image. However I think I found where the error is coming from.

First, let me mention that I re-tested building the image with the original Dockerfile, and then I tested building another image with the addition of the `--setopt=tsflags=nodocs` option.

In both cases the images were created successfully. 
_I have attached two files with the output of each command where you can see the results of the builds._

One thing to notice, though, is that when running `yum -y update`, the command retrieve files from a random mirror server. So, each time we build the image it will be picking a different mirror server.

What I am thinking is that the mirror server selected when you built the image the first time, had a file with some sort of incompatibility, with the centos 7 base-image, that triggered the error.

Can you re-build the image with the original Dockerfile, to confirm that was the cause of the issue?

[test1_without_tsflags.txt](https://github.com/davescripts/docker-centos-7-apache-php-72/files/3694617/test1_without_tsflags.txt)
[test2_with_tsflags.txt](https://github.com/davescripts/docker-centos-7-apache-php-72/files/3694618/test2_with_tsflags.txt)

**Comment by sylvainmetayer** [comment]
I've tried again from my work computer (where the problem was at first) and from my home computer and cannot reproduce it, it build with success now. 

It think that you're right, it was probably a corrupted / incompatible mirror server. 

Sorry for the trouble, and thanks for the detailled explaination !
